name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Build iniciado!"}' $DISCORD_WEBHOOK_URL

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Python script
        run: python3 calculadora.py 1 5 3
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Test iniciado!"}' $DISCORD_WEBHOOK_URL

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t calculadora_python:tag .
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Docker build iniciado!"}' $DISCORD_WEBHOOK_URL

  sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r .
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Análise de segurança iniciada!"}' $DISCORD_WEBHOOK_URL

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job, test-job, docker-build, sast-analysis]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Production
        run: |
          # Adicione aqui os comandos ou scripts necessários para implantar sua aplicação
      - name: Send Discord notification
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Deploy iniciado!"}' $DISCORD_WEBHOOK_URL
