name: CI

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:  
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Python script
        run: python3 calculadora.py 1 5 3

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t nome_da_imagem:tag .
      # Você pode adicionar etapas adicionais para testar a imagem Docker, se necessário

