name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Python script
        run: python3 calculadora.py 1 5 3

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t calculadora_python:tag .

  sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r .

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job, test-job, docker-build, sast-analysis]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Production
        run: |
          # Adicione aqui os comandos ou scripts necessários para implantar sua aplicação
