name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Modificado para abrir o arquivo HTML localmente
      - name: Open HTML file locally
        run: start file:///C:/Users/I558113/Desktop/AS1-DevOps/DevOps---PUCPR/Calculadora.html

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Finalizado"
